/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* To update, please use 'config.json' and run '$ make configs'
*
*/

#ifndef CONFIGS
#define CONFIGS

#define PORT 8080
#define MAX_CONNECTIONS 300
#define MAX_THREADS 2

#endif
