/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* To update, please use 'config.json' and run '$ make configs'
*
*/

#ifndef ERROR_CODES
#define ERROR_CODES

#define ERROR_SOCKET_CREATION 0
#define ERROR_SOCKET_BINDING -1
#define ERROR_SOCKET_REUSABLE -2
#define ERROR_SOCKET_LISTENING -3
#define ERROR_SOCKET_CLIENT_CONNECTION -4
#define ERROR_SOCKET_CLOSING -5
#define ERROR_THREAD_CREATION -6
#define ERROR_THREAD_LIMIT -7
#define ERROR_THREAD_CLOSING -8
#define ERROR_MEMORY_ALLOCATION -9
#define ERROR_UNKNOWN -10

#endif
