#ifndef ERROR_CODES
#define ERROR_CODES

#define ERROR_SOCKET_CREATION -1
#define ERROR_SOCKET_BINDING -2
#define ERROR_SOCKET_REUSABLE -3
#define ERROR_SOCKET_LISTENING -4
#define ERROR_SOCKET_CLIENT_CONNECTION -5
#define ERROR_SOCKET_CLOSING -6

#define ERROR_THREAD_CREATION -11
#define ERROR_THREAD_CLOSING -12

#define ERROR_UNKNOWN -99

#endif